### ISSUE TITLE
When `epsilon==0`, `PrivacyLossDistribution.from_privacy_parameters()` fails.

### ISSUE THREAD

**Issue by ngrislain** [google/differential-privacy#110]
If `epsilon==0` (or small compared to `value_discretization_interval`) then `rounded_probability_mass_function ` is assigned a dict with twice the same key, so the second will overwrite the first (python should probably not silently do that).

https://github.com/google/differential-privacy/blob/fc4f2abda5052f654539fc1282ed64a827465a70/python/dp_accounting/privacy_loss_distribution.py#L582-L587

**Comment by dasmdasm** [comment]
Our [commit](https://github.com/google/differential-privacy/commit/59e27c25e5287c1853cc16a69ddb2b1ce204eba8) last week should have resolved this.
