### ISSUE TITLE
Question about possible wrong merge 

### ISSUE THREAD

**Issue by fbalicchia** [google/differential-privacy#112]
Hi with  [8536a3](https://github.com/google/differential-privacy/commit/8536a3af6b147b1cce6f884826bfd5f2009ae50f)  seems that [61bc5e6f9d2dc5df5f7b9de8071ce3e416bce2f7] was removed.
Is it a wrong merge or is not necessary anymore?

**Comment by dasmdasm** [comment]
Ah, nope, that's a mistake. I missed a step when I accepted your PR. We'd like to revert the deletions, but we also don't want to take away your credit in the commit history, so if you want to send us a revert of those deletions I'd be happy to accept it. Otherwise, I can do it.

**Comment by fbalicchia** [comment]
@dasmdasm np at all. ok i'll revert deletions
