### ISSUE TITLE
Is there a plan to address the issues pointed out in Casacuberta et al?

### ISSUE THREAD

**Issue by sfc-gh-mholboke** [google/differential-privacy#126]
Is there a plan to address this: floating-point implementations are subject to the vulnerabilities described in [Casacuberta et al. "Widespread Underestimation of Sensitivity in Differentially Private Libraries and How to Fix it"](https://arxiv.org/abs/2207.10635) (specifically the rounding, repeated rounding, and re-ordering attacks).

**Comment by dibakch** [comment]
There is a workaround using fixed point.  We did not come to a good solution as of now and there is more work required.  Floating point arithmetic is tricky!
