### ISSUE TITLE
> Is there a plan to address this:loating-point implementations are subject to the vulnerabilities described in [Casacuberta et al. "Widespread Underestimation of Sensitivity in Differentially Private Libraries and How to Fix it"](https://arxiv.org/abs/2207.10635) (specifically the rounding, repeated rounding, and re-ordering attacks).

### ISSUE THREAD

**Issue by senderaleksandr** [google/differential-privacy#127]
> Is there a plan to address this: floating-point implementations are subject to the vulnerabilities described in [Casacuberta et al. "Widespread Underestimation of Sensitivity in Differentially Private Libraries and How to Fix it"](https://arxiv.org/abs/2207.10635) (specifically the rounding, repeated rounding, and re-ordering attacks).

_Originally posted by @senderaleksandr in https://github.com/google/differential-privacy/issues/126#issuecomment-1259607839_

**Comment by FjolleJagt** [comment]
Duplicate of #126
