### ISSUE TITLE
SQL Queries 

### ISSUE THREAD

**Issue by Davealexis97** [google/differential-privacy#138]
I am trying to perform differentially private SQL queries. Are there any walkthroughs to perform this ? I am running into errors when interacting with the ZetaSQL command line interface.

**Comment by miracvbasaran** [comment]
Hey Dave,

Have you looked into the associated [codelab](https://github.com/google/differential-privacy/blob/main/examples/zetasql/codelab.md)? It includes example commands to run.

**Comment by Davealexis97** [comment]
I did, and that is where I am running into the errors. I guess before I started posting some errors I am running into individually, I want to see if there are any walkthroughs, perhaps on YouTube, so I don't clog the issues one by one with errors.

**Comment by miracvbasaran** [comment]
Unfortunately I am not aware of any such walkthroughs, so please feel free to ask away.

**Comment by dibakch** [comment]
Closing this as of inactivity for now.  Feel free to re-open.

@Davealexis97, please feel encouraged to file more issues here with any confusion you might have with the codelab.  Such Feedback would really help us to improve the codelab and documentation over time.  Thanks :)
