### ISSUE TITLE
Why the privacy-on-beam is not implemented by java?

### ISSUE THREAD

**Issue by haoyuche** [google/differential-privacy#139]
The issue of Go is that the IO connectors are quite limited comparing to java: https://beam.apache.org/documentation/io/connectors/.
If we want to apply the DP algorithm to a dataset via beam, go does not have very good IO connector support comparing to java. So is there any initiative that we implement a java version of privacy-on-beam?

**Comment by dibakch** [comment]
There is [PipelineDP](https://github.com/OpenMined/PipelineDP), which is based on Python and can be used with Beam and Spark.  It uses our DP library under the hood.  Would this work for your use case?
