### ISSUE TITLE
anon_func.so file not found

### ISSUE THREAD

**Issue by sastava007** [google/differential-privacy#14]
While building the Postgres database, I'm getting anon_func.so No such file or directory. I tried looking in other folders too, but I couldn't find anything.

Need help!
@google-admin @willnorris @cdibona @dberlin @TedTed 

Here's the screenshot
![image](https://user-images.githubusercontent.com/43990819/71982572-c7d7d180-324a-11ea-8fff-d6475fde52a8.png)

**Comment by dasmdasm** [comment]
It looks like this is covered in our "Common Issues" here: https://github.com/google/differential-privacy/blob/master/differential_privacy/postgres/README.md

Feel free to reopen if those instructions don't solve the issue.
