### ISSUE TITLE
How to setup bounds and epsilon in Anonymous Functions PostgreSQL Extension ?

### ISSUE THREAD

**Issue by AbhishekNalamothu** [google/differential-privacy#15]
@celiayz  When I run the below example query given in the github page, I am getting the following `INFO:  Bin count threshold was too large to find approximate bounds. Either run over a larger dataset or decrease success_probability and try again. Returning NULL.`

```
SELECT result.fruit, result.number_eaten
FROM (
  SELECT per_person.fruit,
    ANON_SUM(per_person.fruit_count, LN(3)/2) as number_eaten,
    ANON_COUNT(uid, LN(3)/2) as number_eaters
    FROM(
      SELECT * , ROW_NUMBER() OVER (
        PARTITION BY uid
        ORDER BY random()
      ) as row_num
      FROM (
        SELECT fruit, uid, COUNT(fruit) as fruit_count
        FROM FruitEaten
        GROUP BY fruit, uid
      ) as per_person_raw
    ) as per_person
  WHERE per_person.row_num <= 5
  GROUP BY per_person.fruit
) as result
WHERE result.number_eaters > 50;
```

![image](https://user-images.githubusercontent.com/16267906/72192120-195a9a80-33ca-11ea-88bd-80745474952c.png)

Could someone give me intuition on how to set bounds and epsilon?

Thanks

**Comment by celiayz** [comment]
Hi, 

The error means that there is not enough data to run the algorithm to automatically get sensitivity bounds. There are a couple ways to solve this

1. Run the query over more data, maybe around 200+ rows.
2. Set epsilon to a much higher number. Epsilon determines the noise distribution added to the underlying result. A larger epsilon means on average, less noise added. LN(3) is our recommended default value, but it could be set to anything depending on use case.
3. Set exact bounds. This can only be done if you have some knowledge about the underlying data. For example, a column of people's ages can likely be bounded by [0, 200].

**Comment by AbhishekNalamothu** [comment]
Thank you so much @celiayz . I will try.
