### ISSUE TITLE
Suggested README updates to cover some postgres build pitfalls

### ISSUE THREAD

**Issue by RacingTadpole** [google/differential-privacy#2]
Thanks for open sourcing this library!
As a newcomer to bazel, I've spent quite a while getting it to build and then getting `CREATE EXTENSION anon_func` to work, and I think highlighting two things in the README would help:

## In the main README: 

You may need to update the paths in `differential-privacy/postgres/BUILD` depending on the system building the binary (eg. `k8-fastbuild` may need to be changed to `darwin-fastbuild`).

## In postgres/README: 

The `install_extension` script assumes postgres is configured to look for extensions in the directory `$PG_DIR/share/extension/`, and that its `$libdir` is `$PG_DIR/lib/`. If you have a pre-existing installation of postgres, your configuration may not fit these path patterns.

If `CREATE EXTENSION anon_func;` fails with an error such as `could not open extension control file "/usr/local/share/postgresql/extension/anon_func.control": No such file or directory`, you will need to move the extensions to that location manually, e.g.:
```
mv $PG_DIR/share/extension/anon_func* /usr/local/share/postgresql/extension/
```
You can then find where to move the `anon_func.so` file to by typing `pg_config  --pkglibdir`, and moving it there, i.e.
```
mv $PG_DIR/lib/anon_func.so `pg_config  --pkglibdir`
```

[Alternatively you might consider generalizing the script to handle this case.]

**Comment by celiayz** [comment]
Thanks for the tip! We will include your suggestions.

**Comment by dasmdasm** [comment]
Just pushed some updates to the documentation that should cover this.
