### ISSUE TITLE
Windows - Cannot open include file: 'libgen.h': No such file or directory 

### ISSUE THREAD

**Issue by adhamai** [google/differential-privacy#20]
I am using windows 10. I got the following error :
ERROR: C:/differentialprivacy/differential-privacy/differential_privacy/base/BUILD:37:1: C++ compilation of rule '//differential_privacy/base:logging' failed (Exit 2)
cl : Command line warning D9002 : ignoring unknown option '-std=c++17'
differential_privacy/base/logging.cc(22): fatal error C1083: Cannot open include file: 'libgen.h': No such file or directory

**Comment by dasmdasm** [comment]
Looks like libgen.h isn't available on windows. Fortunately, it seems like we weren't using it for anything. I've git a code change in progress in remove the include.
