### ISSUE TITLE
Confusing fragment in the java example

### ISSUE THREAD

**Issue by replomancer** [google/differential-privacy#23]
In the [java example](https://github.com/google/differential-privacy/tree/123626ff1060d9884a16f04b0d743a72bb08607e/examples/java) it reads:

> Next, we will demonstrate how to use the library in scenarios where:
> - (...)
> - Visitors can contribute to a partition multiple times.

I believe until the end it is assumed that each visitor contributes at most once to a partition (`.maxContributionsPerPartition` is never used in the example).

**Comment by Kulankhina** [comment]
Hi Łukasz,

Yes, that's a good point, thanks a lot for the feedback!
We are working on the examples demonstrating multiple contributions per partition and we will publish them soon.

Some heads up on this: for [BoundedSum, maxContributionsPerPartition cannot be configured. Instead, the client needs to pre-aggregate contributions coming from the same privacy unit before passing data to the library.  For BoundedMean, the client should configure maxContributionsPerPartition.

[SumRevenuePerDayWithPreAggregation.java](https://github.com/google/differential-privacy/blob/123626ff1060d9884a16f04b0d743a72bb08607e/examples/java/SumRevenuePerDayWithPreAggregation.java) demonstrates how BoundedSum can be used with multiple contributions per partition. More precisely it demonstrates that contributions need to be pre-aggregated, We will soon add the details to the README file.

**Comment by replomancer** [comment]
Hello, Sasha!

Your answer is very clear. Thank you!
