### ISSUE TITLE
Invalid use of `list` type should be `typing.List`

### ISSUE THREAD

**Issue by lucid-jake** [google/differential-privacy#235]
These are invalid uses of the `list` type, which should probably use the `typing.List` class instead.

Thanks!

https://github.com/google/differential-privacy/blob/608350cb93138687393e392f6a9cf542c42678ce/python/dp_accounting/dp_event.py#L291

https://github.com/google/differential-privacy/blob/608350cb93138687393e392f6a9cf542c42678ce/python/dp_accounting/dp_event.py#L352

PS: If this is some advanced use of the lower-case `list` type that I don't understand, then please be gentle, but my project (depending on tensorflow_privacy) won't compile, so... 🤷 

<3

**Comment by lucid-jake** [comment]
BTW, I made this extremely simple change locally and got errors trying to push a new branch for a PR.
Perhaps it's just one of those days, but thanks in advance for the fix! <3

**Comment by lucid-jake** [comment]
Ah, of course! Thanks for the reminder, and the pleasant response pritkamath :)

**Comment by dibakch** [comment]
This has been fixed in e59bbcf86a5febcbbe6b2e5ebea37ee52457cf36

**Comment by Kingcb1** [comment]
>
