### ISSUE TITLE
Relax dependency for scipy~=1.7.1 in dp_accounting

### ISSUE THREAD

**Issue by simonhkswan** [google/differential-privacy#236]
It would be extremely helpful if the `scipy` requirement located here:
 
https://github.com/google/differential-privacy/blob/e59bbcf86a5febcbbe6b2e5ebea37ee52457cf36/python/requirements.txt#LL9C1-L9C13

was changed from 
```
scipy ~= 1.7.1
```

to:
```
scipy ~= 1.7
```

As the former means that anyone using this packaged must use `scipy == 1.7.*`. Looking at the usage of `scipy` in the repo, there doesn't seem be an issue with using `scipy >= 1.8`.

**Comment by dibakch** [comment]
Thanks for the suggestion!  We'll make this change and will push it to GitHub soon (~ within one week).

**Comment by dibakch** [comment]
This has been fixed in commit 2d7cceadf88ad3de6cc305655b8af74c0183147a
