### ISSUE TITLE
Approximate bound maxContributions parameter

### ISSUE THREAD

**Issue by sakkumar** [google/differential-privacy#258]
Hi Team,
How can we dynamically (based on data) determine maxContributions value for approximate bound algorithm? Suppose we do not have any idea about data and would like to find maxContributions value which covers 99.95% of data, can approximate bound implementation support it?

Thanks

**Comment by dvadym** [comment]
@sakkumar we have implementations of approximate bounds for different languages. Which do you mean? [Java version](https://github.com/google/differential-privacy/blob/main/java/main/com/google/privacy/differentialprivacy/ApproximateBounds.java)?

If it's about Java version, then this Algorithm is low-level algorithm and it's assumed to be used by some high-level code. It doesn't have any way to determine which contributions comes from which individual. The code that uses this algorithm should ensure that there are no more than `maxContributions` from one individual. 

For example it can be done by choosing uniformly randomly `maxContributions` contributions for each individual which has more than `maxContributions`. And if you go with this approach, I'd recommend to use `maxContributions=1`.

**Comment by sakkumar** [comment]
choosing maxContributions=1 always is not practical for our use cases as a user can easily contribute to more than 1 partition, we are trying to find maxContributions of user which covers 99.95% of data so that it removes outlier. for e.g. in Ad space, a user can view Ads in more than one campaign. Moreover it is hard to determine maxContributions value beforehand.
I am not sure if there is a differentially private way to determine maxContributions? Or should we just run a query on data and find absolute 99.95% value for user contributions across partitions(e.g. campaigns), which is fed into approximate Bound algo to determine lower & upper bound of metrics (e.g. cost)? Finding absolute 99.95% value might not be considered good option from privacy considerations.

**Comment by dvadym** [comment]
@sakkumar for approximate bounds it's ok from privacy perspective to set `maxContributions=1`, provided you do sampling, `1` contribution per user.
 
Also it should be pretty good from utility perspective (especially if you do sampling uniformly). If shouldn't introduce much additional error. And vice versa if you set `maxContributions` too high, the error can be very large. E.g. if `99.95%` is 100, but the median is `10`. Then the approximate bound algorithm splits the budget over `100`, so the noise will `100` larger.  But `50%` users would contribute only <= 10 times (i.e. for them budget usage is much smaller).

Though, you can experiment with different values of  `maxContributions` (and sampling to the corresponding value).

Note: for other DP aggregations, sampling might have introduce additional error. For example for computing COUNT.  If we set  `maxContributions=1` for DP Count and do sampling, then much data can be lost with sampling and the result is biased downwards.

**Comment by dvadym** [comment]
@sakkumar Sry for late reply. 

No, I meant the following scheme:

1. For each user, from all contributions of this user to sample `1` contribution.
2. The data after sampling is used as input of aproximate bounds algorithm.

Then I realized, that it assumes that it is known which data points come from which user. Do you have this information? If yes, that the sampling is the best option (it ensures DP for all users and it's good for utility of this algorithm)

If you can not do sampling, then choosing `maxContributions` which larger that very high percentale of users (e.g. 99.95%) seems to be reasonable tradeoff.

**Comment by sakkumar** [comment]
We are thinking of doing below steps:
1. find maxContributions value which covers 99.95% percentile of data
2. Sample per user data to satisfy maxContributions upper bound
3. Find approximate bound of metrics/cols using maxContributions
