### ISSUE TITLE
Build error on differential-privacy/cc  on ubuntu18.04

### ISSUE THREAD

**Issue by uishi** [google/differential-privacy#26]
Would you have some suggestion to fix the following error?

cd cc
bazel build //...

INFO: Analyzed 56 targets (0 packages loaded, 0 targets configured).
INFO: Found 56 targets...
ERROR: /home/username/differential-privacy/cc/algorithms/BUILD:37:8: C++ compilation of rule '//algorithms:algorithm_test' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF ... (remaining 76 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from ./algorithms/algorithm.h:27,
                 from algorithms/algorithm_test.cc:17:
./algorithms/numerical-mechanisms.h: In member function 'double differential_privacy::GaussianMechanism::CalculateDelta(double, double)':
./algorithms/numerical-mechanisms.h:517:9: error: 'isinf' was not declared in this scope
     if (isinf(b)) {
         ^~~~~
./algorithms/numerical-mechanisms.h:517:9: note: suggested alternative:
In file included from external/com_google_absl/absl/hash/internal/hash.h:24,
                 from external/com_google_absl/absl/hash/hash.h:73,
                 from external/com_google_absl/absl/container/internal/hash_function_defaults.h:55,
                 from external/com_google_absl/absl/container/node_hash_map.h:45,
                 from ./base/status.h:26,
                 from ./algorithms/algorithm.h:26,
                 from algorithms/algorithm_test.cc:17:
/usr/include/c++/8/cmath:605:5: note:   'std::isinf'
     isinf(_Tp __x)
     ^~~~~
In file included from ./algorithms/bounded-standard-deviation.h:26,
                 from postgres/dp_func.cc:21:
./algorithms/bounded-variance.h: In instantiation of 'differential_privacy::BoundedVariance<T, <anonymous> >::BoundedVariance(double, T, T, double, double, std::unique_ptr<differential_privacy::LaplaceMechanism::Builder, std::default_delete<differential_privacy::LaplaceMechanism::Builder> >, std::unique_ptr<differential_privacy::NumericalMechanism>, std::unique_ptr<differential_privacy::NumericalMechanism>, std::unique_ptr<differential_privacy::NumericalMechanism>, std::unique_ptr<differential_privacy::ApproxBounds<T> >) [with T = double; std::enable_if_t<std::is_arithmetic<_Tp>::value>* <anonymous> = 0]':
./algorithms/bounded-variance.h:135:31:   required from 'differential_privacy::base::StatusOr<std::unique_ptr<differential_privacy::BoundedVariance<T> > > differential_privacy::BoundedVariance<T, <anonymous> >::Builder::BuildAlgorithm() [with T = double; std::enable_if_t<std::is_arithmetic<_Tp>::value>* <anonymous> = 0; std::enable_if_t<std::is_arithmetic<_Tp>::value> = void]'
./algorithms/bounded-variance.h:93:57:   required from here
./algorithms/bounded-variance.h:481:16: warning: 'differential_privacy::BoundedVariance<double, 0>::linf_sensitivity_' will be initialized after [-Wreorder]
   const double linf_sensitivity_;
                ^~~~~~~~~~~~~~~~~
./algorithms/bounded-variance.h:479:46: warning:   'std::unique_ptr<differential_privacy::LaplaceMechanism::Builder, std::default_delete<differential_privacy::LaplaceMechanism::Builder> > differential_privacy::BoundedVariance<double, 0>::mechanism_builder_' [-Wreorder]
   std::unique_ptr<LaplaceMechanism::Builder> mechanism_builder_;
                                              ^~~~~~~~~~~~~~~~~~
./algorithms/bounded-variance.h:276:3: warning:   when initialized here [-Wreorder]
   BoundedVariance(const double epsilon, const T lower, const T upper,
   ^~~~~~~~~~~~~~~
In file included from postgres/dp_func.cc:20:
./algorithms/bounded-mean.h: In instantiation of 'differential_privacy::BoundedMean<T, <anonymous> >::BoundedMean(double, T, T, double, double, std::unique_ptr<differential_privacy::LaplaceMechanism::Builder, std::default_delete<differential_privacy::LaplaceMechanism::Builder> >, std::unique_ptr<differential_privacy::NumericalMechanism>, std::unique_ptr<differential_privacy::NumericalMechanism>, std::unique_ptr<differential_privacy::ApproxBounds<T> >) [with T = double; std::enable_if_t<std::is_arithmetic<_Tp>::value>* <anonymous> = 0]':
./algorithms/bounded-mean.h:107:11:   required from 'differential_privacy::base::StatusOr<std::unique_ptr<differential_privacy::BoundedMean<T> > > differential_privacy::BoundedMean<T, <anonymous> >::Builder::BuildAlgorithm() [with T = double; std::enable_if_t<std::is_arithmetic<_Tp>::value>* <anonymous> = 0; std::enable_if_t<std::is_arithmetic<_Tp>::value> = void]'
./algorithms/bounded-mean.h:72:53:   required from here
./algorithms/bounded-mean.h:325:16: warning: 'differential_privacy::BoundedMean<double, 0>::linf_sensitivity_' will be initialized after [-Wreorder]
   const double linf_sensitivity_;
                ^~~~~~~~~~~~~~~~~
./algorithms/bounded-mean.h:323:46: warning:   'std::unique_ptr<differential_privacy::LaplaceMechanism::Builder, std::default_delete<differential_privacy::LaplaceMechanism::Builder> > differential_privacy::BoundedMean<double, 0>::mechanism_builder_' [-Wreorder]
   std::unique_ptr<LaplaceMechanism::Builder> mechanism_builder_;
                                              ^~~~~~~~~~~~~~~~~~
./algorithms/bounded-mean.h:210:3: warning:   when initialized here [-Wreorder]
   BoundedMean(const double epsilon, T lower, T upper,
   ^~~~~~~~~~~
In file included from postgres/dp_func.cc:22:
./algorithms/bounded-sum.h: In instantiation of 'differential_privacy::BoundedSum<T, <anonymous> >::BoundedSum(double, T, T, double, double, std::unique_ptr<differential_privacy::LaplaceMechanism::Builder, std::default_delete<differential_privacy::LaplaceMechanism::Builder> >, std::unique_ptr<differential_privacy::NumericalMechanism>, std::unique_ptr<differential_privacy::ApproxBounds<T> >) [with T = double; std::enable_if_t<std::is_arithmetic<_Tp>::value>* <anonymous> = 0]':
./algorithms/bounded-sum.h:82:11:   required from 'differential_privacy::base::StatusOr<std::unique_ptr<differential_privacy::BoundedSum<T> > > differential_privacy::BoundedSum<T, <anonymous> >::Builder::BuildAlgorithm() [with T = double; std::enable_if_t<std::is_arithmetic<_Tp>::value>* <anonymous> = 0; std::enable_if_t<std::is_arithmetic<_Tp>::value> = void]'
./algorithms/bounded-sum.h:60:52:   required from here
./algorithms/bounded-sum.h:335:16: warning: 'differential_privacy::BoundedSum<double, 0>::linf_sensitivity_' will be initialized after [-Wreorder]
   const double linf_sensitivity_;
                ^~~~~~~~~~~~~~~~~
./algorithms/bounded-sum.h:333:46: warning:   'std::unique_ptr<differential_privacy::LaplaceMechanism::Builder, std::default_delete<differential_privacy::LaplaceMechanism::Builder> > differential_privacy::BoundedSum<double, 0>::mechanism_builder_' [-Wreorder]
   std::unique_ptr<LaplaceMechanism::Builder> mechanism_builder_;
                                              ^~~~~~~~~~~~~~~~~~
./algorithms/bounded-sum.h:199:3: warning:   when initialized here [-Wreorder]
   BoundedSum(double epsilon, T lower, T upper, const double l0_sensitivity,
   ^~~~~~~~~~
INFO: Elapsed time: 3.807s, Critical Path: 3.63s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

**Comment by dasmdasm** [comment]
Ah, oops. We should have called that std::isinf. A fix is on the way.

**Comment by miguelagt** [comment]
Hey uishi: 

I work at Google with dasmdasm. I was wondering if I can have a chat with you to learn more about your usage of the library. We are looking for stories of our users to understand more about its usage. 

If you're open to a chat, let me know how can I reach you. 

Best

**Comment by devansh1305** [comment]
Hey I am also getting the same error

```
bash_prompt:~/differential-privacy/cc$ sudo bazel build ...
INFO: Analyzed 56 targets (0 packages loaded, 0 targets configured).
INFO: Found 56 targets...
ERROR: /home/user/differential-privacy/cc/algorithms/BUILD:37:8: C++ compilation of rule '//algorithms:algorithm_test' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF ... (remaining 76 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from ./algorithms/algorithm.h:27:0,
                 from algorithms/algorithm_test.cc:17:
./algorithms/numerical-mechanisms.h: In member function 'double differential_privacy::GaussianMechanism::CalculateDelta(double, double)':
./algorithms/numerical-mechanisms.h:517:9: error: 'isinf' was not declared in this scope
     if (isinf(b)) {
         ^~~~~
./algorithms/numerical-mechanisms.h:517:9: note: suggested alternative:
In file included from external/com_google_absl/absl/hash/internal/hash.h:24:0,
                 from external/com_google_absl/absl/hash/hash.h:73,
                 from external/com_google_absl/absl/container/internal/hash_function_defaults.h:55,
                 from external/com_google_absl/absl/container/node_hash_map.h:45,
                 from ./base/status.h:26,
                 from ./algorithms/algorithm.h:26,
                 from algorithms/algorithm_test.cc:17:
/usr/include/c++/7/cmath:612:5: note:   'std::isinf'
     isinf(_Tp __x)
     ^~~~~
INFO: Elapsed time: 3.169s, Critical Path: 2.98s
INFO: 9 processes: 9 linux-sandbox.
FAILED: Build did NOT complete successfully
```
I found this thread here, maybe it may be of some help...
[https://github.com/facebookresearch/Starspace/issues/34#issuecomment-329561079](url)

**Comment by dasmdasm** [comment]
This was fixed with https://github.com/google/differential-privacy/commit/0b0a5c2315d84a6a7b1ff34591e33ec11680891e
