### ISSUE TITLE
[privacy-on-beam] codelab uses 2 packages

### ISSUE THREAD

**Issue by bamnet** [google/differential-privacy#28]
Currently the privacy-on-beam codelab uses two different go packages in the same folder which is valid syntax using Bazel, but not  native go commands.  As a result, you can `bazel run` the codelab, but not `go run` it.

Have we considered condensing the codelab into 1 package (or splitting it into 2 folders) so it can run using native go commands?

I'm _not_ suggesting to remove Bazel entirely, but to sure the barrier of entry is as low as possible for people who just want to run a codelab and see what happens.

**Comment by miracvbasaran** [comment]
Privacy on Beam codelab has a single `codelab` package and a `main` package. Should main packages live in a different directory for `go run` to work?

**Comment by bamnet** [comment]
Yep! The main package (or codelab package.. either one) needs to live in a different directory for `go run` to work without Bazel.

**Comment by miracvbasaran** [comment]
`go build/test/run` should work for all the go-related code in the repository starting from v1.1.0.
