### ISSUE TITLE
Generate First Release

### ISSUE THREAD

**Issue by Tata17** [google/differential-privacy#4]
Hello there, 
Would it be possible for you to generate a release for differential-privacy? Thanks!

**Comment by rluria14** [comment]
bump

**Comment by rluria14** [comment]
Since are no tarball files released for this package here on GitHub or on PyPi, is it possible to generate/compile one either here or on pypi. Working on building this for conda-forge.

Thank you!

**Comment by rluria14** [comment]
@dasmdasm

**Comment by dibakch** [comment]
Closing this as we have released 1.0.0 already.
