### ISSUE TITLE
postgres: "anon_count" crashes on emtpy subquery

### ISSUE THREAD

**Issue by sebastian-sohr** [google/differential-privacy#5]
Hallo,
connection is lost when (e.g.) "ANON_COUNT" applied to a subquery which yields no resuls:
```
dp_test=> select ANON_COUNT(ID) from ( select ID from  ( select 1 as ID ) as A where ID = 2 ) as A;
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!> 
```
in squirrel (jdbc): 
```
Error: An I/O error occurred while sending to the backend.
SQLState:  08006
ErrorCode: 0

```
In my opinion, this violates the basic principle of differential privacy : You find out that no entry with given signature exists.

Regards,
Sebastian.

**Comment by celiayz** [comment]
Hi Sebastian,

Thanks for notifying us about this. We will push a change to return NULL rather than lose connection. Unfortunately, you are correct that we will not be providing differential privacy for the empty input set case. We will add a comment in the documentation to this effect.

Best,
Celia

**Comment by sebastian-sohr** [comment]
Many thanks!
Just a remark how to provide differential privacy in a situation where analysts may specify the restrictions of a statements which is otherwise controlled by the service provider:
Use left join of all ids with restricted data set:

```
with
        FACTS
as
        (
                select
                        1 as ID,
                        5 as D
                union all
                select
                        2 as ID,
                        7 as D
        )
select
        anon_count(data.ID)
from
        (
                select
                        ids.ID,
                        data.D
                from
                        (
                                select
                                        ID
                                from
                                        FACTS
                        ) as ids
                        left join
                        (
                                select
                                        ID,
                                        D
                                from
                                        FACTS
                                where
                                        ID = 3
                        ) as data
                                on
                                ids.ID = data.ID
        ) as data
;

```
The restriction conditions within "data" may be controlled by the service user. By imbedding them in the query with "left join", getting an empty query result is prevented and the real count "0" is disguised correctly.
