### ISSUE TITLE
Can not build the c++ library

### ISSUE THREAD

**Issue by Tarik-ala** [google/differential-privacy#55]
Hi,
I am trying to build the C++ library on Linux Arch and I keep encountering the same problem over and over again. I attached the log file, the error occurs at line 39809, any ideas why this happens? Thanks in advance for the help. 

[Log.txt](https://github.com/google/differential-privacy/files/5305957/Log.txt)

**Comment by dasmdasm** [comment]
See this comment: https://github.com/google/differential-privacy/blob/main/cc/postgres/BUILD#L43

You likely need to update those paths for your system.

**Comment by Tarik-ala** [comment]
Hi, thanks for the help but even after I change the paths from "k8-fastbuild" to "darwin-fastbuild" i get the same error. Is there some other path that needs to be changed? The error in this log file is 39046.
[debug.txt](https://github.com/google/differential-privacy/files/5410611/debug.txt)

**Comment by rjwilson** [comment]
The error in your log that I see is:
```
bazel-out/k8-fastbuild/bin/external/postgres/postgres/logs/Configure_script.sh: line 38: make: command not found
```
Do you have make installed? Try:
```
sudo apt-get install make
```

**Comment by Tarik-ala** [comment]
Ahh my bad, thanks for help that fixed it.
