### ISSUE TITLE
C++ Proposal: Remove privacy_budget parameter

### ISSUE THREAD

**Issue by dasmdasm** [google/differential-privacy#59]
This is a proposed change to the C++ building blocks library. I'm posting it here to solicit feedback and suggestions before we make a final call on implementing it.

Currently all `Algorithm`s offer the ability to get a result while only spending part of an internal "privacy budget." This is implemented as using a user-specified fraction of the `Algorithm`'s epsilon for each calculation, and tracking how much epsilon remains. In our experience this functionality doesn't get much use, and adds the extra complexity of tracking each internal "privacy budget." It's also just plain not that useful - anyone who wants to track overall expenditure of privacy loss budget will need to do extra work as soon as they're using more than one `Algorithm`.

As a simplification, we'd like to remove the ability to specify a privacy budget fraction when getting a result. `Algorithms` will only be able to return a single result for a set of input, and will have to be reset before being used again.

**Comment by dibakch** [comment]
This proposal has been implemented.
