### ISSUE TITLE
Postgres install not working - part 2

### ISSUE THREAD

**Issue by cj-wilson** [google/differential-privacy#69]
I'm getting the following error after following the documentation explicitly.  I'm not a Bazel expert, so a little more information would be helpful if this traces back to a Bazel issue.  Thank you.

On issue I think I'm running into is the Postgres 11.x source apparently points to v12 regardless of how I try and set it through ./configure.  I've tried to symlink these but still the same error.  Thank you in advance.

PKGLIBDIR = /usr/lib/postgresql/12/lib
SHAREDIR = /usr/share/postgresql/12

ERROR: /root/.cache/bazel/_bazel_root/30b75978bb371428f4a3fb652d2a1ed8/external/com_google_protobuf/BUILD:1006:21: in proto_lang_toolchain rule @com_google_protobuf//:cc_toolchain: '@com_google_protobuf//:cc_toolchain' does not have mandatory provider 'ProtoInfo'.
ERROR: Analysis of target '//postgres:anon_func.so' failed; build aborted: Analysis of target '@com_google_protobuf//:cc_toolchain' failed

**Comment by rjwilson** [comment]
How did you install postgres?
What command(s) are you invoking to build/install the postgres extension?
Can you include the output of `pg_config`?

**Comment by cj-wilson** [comment]
Here is a quick overview of how I solved this problem.  Please keep in mind I do NOT know Bazel, but was able to 'Google' enough to get by.

1. The docs outlined Postgres 11, but digging deeper I found that Posgress 11_7 was being pulled by Bazel and wound up using that distribution.
2. Postgres 11 install docs use /usr/local/pgsql, but pg_config show /usr/[lib|include]/postgresql as base directories regardless if I compiled them to use /usr/local/pgsql/[lib|include]
3. I really had to dig into Bazel build and set --incompatible_require_linker_input_cc_api=false 
4. I also walked through each directory for Go, Python, Java, etc. and executed a bazel build ...:all in each
5. In the end errcodes.h was not where Bazel thought it was and I had to move it from the compiled Postgres location into the ~/.cache/bazel/_bazel_posgres/GUID/external/postgres/src/include/utils/ directory.  Then it worked!

I also found that the install script was set for a darwin, and I'm running Ubuntu.  Could have been RHEL, but I edited that script and the postgres.BUILD file to line up those variables.  

Lastly, the protocol buffers from Github on the documented version are out of date (or broken).  I updated the differential_privacy_deps.bzl with the following below.  This and the 'errcodes.h' location took the most time. For my two cents, please test on a variant of Linux that's documented up front. I knew I was up for it when I saw the darwin refs, if you could run it on VirtualBox or other that'd be helpful.

    http_archive(
        name = "com_google_protobuf",
        urls = ["https://github.com/protocolbuffers/protobuf/archive/master.tar.gz"],
        sha256 = "27dcdb2f75a84bb0c6101509f69abc9c1c2ba90ae3ae7567bf3f613d771ea4e1",
        strip_prefix = "protobuf-master",
    )

**Comment by dibakch** [comment]
Thanks for reporting!  This might be related to the Bazel 4.0.0 release.  Could you run `bazel --version`?

**Comment by cj-wilson** [comment]
4.0.0 it is!

**Comment by dibakch** [comment]
Bazel 4.0.0 just got released and some of our dependencies require some features that just got deprecated in that version.  You need to use the 3.7.2 version for building our library.  We are pinning the bazel version to 3.7.2 with the next push.

Thanks for reporting this!
