### ISSUE TITLE
Set User Contribution for Mean

### ISSUE THREAD

**Issue by ReichertL** [google/differential-privacy#72]
Hello,
I am trying to calculate a Differentially Private Mean over a data set where each user contributes about 10 entries. 
According to the paper referenced in the Readme this library supports this operation. 

I found the function SetMaxContributionsPerPartition() in algrorithm.h, but from the docs and the comments it is not clear to me if this functions does what I need.

It would be great, if you could help me with this.

**Comment by dasmdasm** [comment]
I've drafted some additions to the documentation, thanks for pointing out the gap.

SetMaxContributionsPerPartition is indeed how you tell the library how many contributions each user makes. The noise will be scaled up to account for the fact that each user has more of an effect on the outcome. Note that it's on you as the caller to make sure that no user contributes more than the limit you set. You should assume that the aggregation result reveals the parameter you set, so it is not differentially private to set the parameter with private information.

**Comment by ReichertL** [comment]
Hello,
Thanks for the answer. So if I use this function to set the user contribution to k, will this cause epsilon to be divided by k? For example as it would be done for groups? (see "The Algorithmic Foundations of Differential Privacy", Theorem 2.2)

**Comment by dasmdasm** [comment]
Technically it's modifying the sensitivity. For all the noise types we use today that's equivalent to dividing epsilon by k. I wouldn't really recommend using this setting to implement group privacy - it's more intended to account for a single user having multiple records.

**Comment by ReichertL** [comment]
Thank you for the clarification.
