### ISSUE TITLE
Support bazel 4.x.x

### ISSUE THREAD

**Issue by bamnet** [google/differential-privacy#79]
In #70, bazel was pinned to version 3.7.2 because of challenges with some dependencies.

The recently released [fully-homomorphic-encryption](https://github.com/google/fully-homomorphic-encryption/) library requires bazel 4.0.0, which means I now need two competing bazel installations to experiment with Google's privacy building blocks. It would be great if this differential-privacy library could catch up so I could blow away the old bazel version.

**Comment by dibakch** [comment]
Thanks for pointing this out!  I would recommend using [Bazelisk](https://docs.bazel.build/versions/main/install-bazelisk.html) for Bazel projects.  Bazelisk is a Bazel launcher that automatically downloads the required Bazel version.

**Comment by dibakch** [comment]
Closing this as we are now switched to Bazel 4.1.0
